#!/usr/bin/env bash

result=0

echo "Running cargo fmt check..."
cargo fmt --check || result=1

echo "Running cargo clippy..."
cargo clippy -- -D warnings || result=1

echo "Running cargo test..."
cargo test || result=1

exit $result
