# Help: https://docs.github.com/en/actions/tutorials/build-and-test-code/rust
name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TARGET: [release]
    steps:
      - uses: actions/checkout@v6
      - name: Run cargo clippy
        run: cargo clippy --profile ${{ matrix.BUILD_TARGET }}
      - name: Run cargo fmt
        run: cargo fmt --check
      - name: Build binaries in "${{ matrix.BUILD_TARGET }}" mode
        run: cargo build --profile ${{ matrix.BUILD_TARGET }}
      - name: Run tests in "${{ matrix.BUILD_TARGET }}" mode
        run: cargo test --profile ${{ matrix.BUILD_TARGET }}
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: openapi2skill
          path: target/${{ matrix.BUILD_TARGET }}/openapi2skill
